# Generated by Django 6.1 on 2026-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinophile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], default='movie', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='status',
            field=models.CharField(choices=[('plan_to_watch', 'Plan to Watch'), ('watching', 'Currently Watching'), ('completed', 'Completed')], default='plan_to_watch', max_length=20),
        ),
    ]
