# Generated by Django 6.1 on 2026-08-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinophile_app', '0002_watchlistitem_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='media_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV', 'TV')], default='Movie', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='status',
            field=models.CharField(choices=[('Plan to Watch', 'Plan to Watch'), ('Watching', 'Watching'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Plan to Watch', max_length=50),
        ),
    ]
