# Generated by Django 6.1 on 2026-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinophile_app', '0003_alter_watchlistitem_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
